In [3]:
import requests
from bs4 import BeautifulSoup

# Fetch the web page
url = 'https://ischoolconnect.com/blog/list-of-100-graduate-schools-with-low-gpa-requirements/'
response = requests.get(url)

# Parse the page
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table element
table = soup.find('table')

# Initialize lists to store data
universities = []
cgpa_requirements = []

# Loop through rows in the table
for row in table.find_all('tr'):
    columns = row.find_all('td')
    if len(columns) == 2:
        university = columns[0].text.strip()
        cgpa = columns[1].text.strip()
        universities.append(university)
        cgpa_requirements.append(cgpa)

# Print the data
for i in range(len(universities)):
    print(f"University: {universities[i]}")
    print(f"CGPA Requirement: {cgpa_requirements[i]}")
    print()

AttributeError: 'NoneType' object has no attribute 'find_all'

In [2]:
!pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in d:\data_science\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in d:\data_science\lib\site-packages (from beautifulsoup4) (2.3.1)

In [21]:
import requests
from bs4 import BeautifulSoup
import pandas as pd 
# Specify the URL

url = 'https://ischoolconnect.com/blog/list-of-100-graduate-schools-with-low-gpa-requirements/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'}
response = requests.get(url, headers=headers)


# Send a GET request to the URL


# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the table element
    tables = soup.find_all('table')

    # Initialize lists to store data
    universities = []
    cgpa_requirements = []

    # Loop through rows in the table
    for table in tables:
        
        for row in table.find_all('tr'):
            columns = row.find_all('td')
            if len(columns) == 2:
                university = columns[0].text.strip()
                cgpa = columns[1].text.strip()
                universities.append(university)
                cgpa_requirements.append(cgpa)

    # Print the data
        for i in range(len(universities)):
            data={"Universities":universities[i],
                 "GPA":cgpa_requirements[i]}
            print(data)

            
else:
    print(f"Failed to retrieve the page. Status code: {response.status_code}")

{'Universities': 'Universities', 'GPA': 'CGPA'}
{'Universities': 'University of Arkansas at Little Rock', 'GPA': '2.0'}
{'Universities': 'University of Colorado at Colorado Springs', 'GPA': '3.25'}
{'Universities': 'Western Governors University', 'GPA': '2.0'}
{'Universities': 'University of Louisiana at Monroe', 'GPA': '2.5'}
{'Universities': 'The University of Maine at Presque Isle', 'GPA': '2.5'}
{'Universities': 'University of Maryland Eastern Shore', 'GPA': '3.5'}
{'Universities': 'The University of Massachusetts Dartmouth –', 'GPA': '3.3'}
{'Universities': 'Albany State University', 'GPA': '3.0'}
{'Universities': 'Liberty University', 'GPA': '2.5'}
{'Universities': 'Dallas Nursing Institute', 'GPA': '2.0'}
{'Universities': 'Family of Faith Christian University', 'GPA': '2.0'}
{'Universities': 'Fort Hays State University', 'GPA': '2.5'}
{'Universities': 'Gwynedd Mercy University', 'GPA': '3.0'}
{'Universities': 'Lewis Clark State College', 'GPA': '2.0'}
{'Universities': 'Medaille College', 'GPA': '3.11'}
{'Universities': 'Purdue University Global', 'GPA': '2.5 – may accept students with low GPAs based on other aspects of their profiles'}
{'Universities': 'North Carolina State University', 'GPA': '3.0'}
{'Universities': 'Texas A&M International University', 'GPA': '3.0'}
{'Universities': 'University of Houston, Clear Lake', 'GPA': '3.0'}
{'Universities': 'University of Maine', 'GPA': '3.3'}
{'Universities': 'West Texas A&M University', 'GPA': '3.0'}
{'Universities': 'Troy University Troy, Alabama', 'GPA': '3.4'}
{'Universities': 'ECPI', 'GPA': '2.5'}
{'Universities': 'Endicott College', 'GPA': '3.0'}
{'Universities': 'Grace Christian University', 'GPA': '3.0'}
{'Universities': 'University of Southern Indiana', 'GPA': '3.0'}
{'Universities': 'California State University San Bernardino, California', 'GPA': '3.0'}
{'Universities': 'Southern New Hampshire University', 'GPA': '2.75'}
{'Universities': 'Bloomsburg University of Pennsylvania', 'GPA': '2.7'}
{'Universities': 'Lamar University', 'GPA': '2.5'}
{'Universities': 'The College of Westchester', 'GPA': '3.15'}
{'Universities': 'Massachusetts State University', 'GPA': '2.75'}
{'Universities': 'Capella University', 'GPA': '2.8 – may accept students with low GPAs based on other aspects of their profiles'}
{'Universities': 'Cal Poly Pomona', 'GPA': '2.5'}
{'Universities': 'California State University East Bay', 'GPA': '2.5'}
{'Universities': 'Universities', 'GPA': 'CGPA'}
{'Universities': 'University of Arkansas at Little Rock', 'GPA': '2.0'}
{'Universities': 'University of Colorado at Colorado Springs', 'GPA': '3.25'}
{'Universities': 'Western Governors University', 'GPA': '2.0'}
{'Universities': 'University of Louisiana at Monroe', 'GPA': '2.5'}
{'Universities': 'The University of Maine at Presque Isle', 'GPA': '2.5'}
{'Universities': 'University of Maryland Eastern Shore', 'GPA': '3.5'}
{'Universities': 'The University of Massachusetts Dartmouth –', 'GPA': '3.3'}
{'Universities': 'Albany State University', 'GPA': '3.0'}
{'Universities': 'Liberty University', 'GPA': '2.5'}
{'Universities': 'Dallas Nursing Institute', 'GPA': '2.0'}
{'Universities': 'Family of Faith Christian University', 'GPA': '2.0'}
{'Universities': 'Fort Hays State University', 'GPA': '2.5'}
{'Universities': 'Gwynedd Mercy University', 'GPA': '3.0'}
{'Universities': 'Lewis Clark State College', 'GPA': '2.0'}
{'Universities': 'Medaille College', 'GPA': '3.11'}
{'Universities': 'Purdue University Global', 'GPA': '2.5 – may accept students with low GPAs based on other aspects of their profiles'}
{'Universities': 'North Carolina State University', 'GPA': '3.0'}
{'Universities': 'Texas A&M International University', 'GPA': '3.0'}
{'Universities': 'University of Houston, Clear Lake', 'GPA': '3.0'}
{'Universities': 'University of Maine', 'GPA': '3.3'}
{'Universities': 'West Texas A&M University', 'GPA': '3.0'}
{'Universities': 'Troy University Troy, Alabama', 'GPA': '3.4'}
{'Universities': 'ECPI', 'GPA': '2.5'}
{'Universities': 'Endicott College', 'GPA': '3.0'}
{'Universities': 'Grace Christian University', 'GPA': '3.0'}
{'Universities': 'University of Southern Indiana', 'GPA': '3.0'}
{'Universities': 'California State University San Bernardino, California', 'GPA': '3.0'}
{'Universities': 'Southern New Hampshire University', 'GPA': '2.75'}
{'Universities': 'Bloomsburg University of Pennsylvania', 'GPA': '2.7'}
{'Universities': 'Lamar University', 'GPA': '2.5'}
{'Universities': 'The College of Westchester', 'GPA': '3.15'}
{'Universities': 'Massachusetts State University', 'GPA': '2.75'}
{'Universities': 'Capella University', 'GPA': '2.8 – may accept students with low GPAs based on other aspects of their profiles'}
{'Universities': 'Cal Poly Pomona', 'GPA': '2.5'}
{'Universities': 'California State University East Bay', 'GPA': '2.5'}
{'Universities': 'CSU Fresno', 'GPA': '2.5'}
{'Universities': 'California State University Fullerton', 'GPA': '3.0'}
{'Universities': 'CSU Long Beach', 'GPA': '2.5'}
{'Universities': 'California State University Northridge', 'GPA': '3.0'}
{'Universities': 'Grand Canyon University', 'GPA': '3.0 – this is valid for most programs at the university, except for some like Ph.D. in General Psychology, which needs a 3.4 GPA'}
{'Universities': 'DePaul University', 'GPA': '2.5'}
{'Universities': 'Eastern Michigan University', 'GPA': '3.0'}
{'Universities': 'Gannon University', 'GPA': '3.5'}
{'Universities': 'Humboldt State University', 'GPA': '2.7'}
{'Universities': 'Jackson state university', 'GPA': '3.0'}
{'Universities': 'Full Sail University Winter Park, Florida', 'GPA': '2.0 – This is one of the Universities that accept low GPA for graduate programs'}
{'Universities': 'University of Minnesota Twin Cities', 'GPA': '3.0'}
{'Universities': 'Fresno City College', 'GPA': '2.0'}
{'Universities': 'Vorhees College', 'GPA': '2.0'}
{'Universities': 'Livingstone College', 'GPA': '2.32'}
{'Universities': 'McHenry County College', 'GPA': '2.0'}
{'Universities': 'Arkansas Tech University Russellville, Arkansas', 'GPA': '2.5'}
{'Universities': 'South Suburban College', 'GPA': '2.0'}
{'Universities': 'Southern University at New Orleans', 'GPA': '3.0'}
{'Universities': 'Talladega College', 'GPA': '2.0'}
{'Universities': 'Richland Community College', 'GPA': '2.15'}
{'Universities': 'Louisburg College', 'GPA': '2.0'}
{'Universities': 'Metropolitan College of New York', 'GPA': '2.5'}
{'Universities': 'National University San Diego, California', 'GPA': '2.0'}
{'Universities': 'Virginia University of Lynchburg', 'GPA': '2.8'}
{'Universities': 'Benjamin Franklin Institute of Technology', 'GPA': '3.15'}
{'Universities': 'Southeast Technical Institute', 'GPA': '3.3'}
{'Universities': 'University of the West', 'GPA': '3.25'}
{'Universities': 'Nebraska Wesleyan University Lincoln, Nebraska', 'GPA': '2.67'}
{'Universities': 'The University of North Carolina at Pembroke', 'GPA': '3.0'}
{'Universities': 'University of Pittsburgh at Bradford', 'GPA': '3.31'}
{'Universities': 'The University of South Carolina Beaufort', 'GPA': '3.5'}
{'Universities': 'Universities', 'GPA': 'CGPA'}
{'Universities': 'University of Arkansas at Little Rock', 'GPA': '2.0'}
{'Universities': 'University of Colorado at Colorado Springs', 'GPA': '3.25'}
{'Universities': 'Western Governors University', 'GPA': '2.0'}
{'Universities': 'University of Louisiana at Monroe', 'GPA': '2.5'}
{'Universities': 'The University of Maine at Presque Isle', 'GPA': '2.5'}
{'Universities': 'University of Maryland Eastern Shore', 'GPA': '3.5'}
{'Universities': 'The University of Massachusetts Dartmouth –', 'GPA': '3.3'}
{'Universities': 'Albany State University', 'GPA': '3.0'}
{'Universities': 'Liberty University', 'GPA': '2.5'}
{'Universities': 'Dallas Nursing Institute', 'GPA': '2.0'}
{'Universities': 'Family of Faith Christian University', 'GPA': '2.0'}
{'Universities': 'Fort Hays State University', 'GPA': '2.5'}
{'Universities': 'Gwynedd Mercy University', 'GPA': '3.0'}
{'Universities': 'Lewis Clark State College', 'GPA': '2.0'}
{'Universities': 'Medaille College', 'GPA': '3.11'}
{'Universities': 'Purdue University Global', 'GPA': '2.5 – may accept students with low GPAs based on other aspects of their profiles'}
{'Universities': 'North Carolina State University', 'GPA': '3.0'}
{'Universities': 'Texas A&M International University', 'GPA': '3.0'}
{'Universities': 'University of Houston, Clear Lake', 'GPA': '3.0'}
{'Universities': 'University of Maine', 'GPA': '3.3'}
{'Universities': 'West Texas A&M University', 'GPA': '3.0'}
{'Universities': 'Troy University Troy, Alabama', 'GPA': '3.4'}
{'Universities': 'ECPI', 'GPA': '2.5'}
{'Universities': 'Endicott College', 'GPA': '3.0'}
{'Universities': 'Grace Christian University', 'GPA': '3.0'}
{'Universities': 'University of Southern Indiana', 'GPA': '3.0'}
{'Universities': 'California State University San Bernardino, California', 'GPA': '3.0'}
{'Universities': 'Southern New Hampshire University', 'GPA': '2.75'}
{'Universities': 'Bloomsburg University of Pennsylvania', 'GPA': '2.7'}
{'Universities': 'Lamar University', 'GPA': '2.5'}
{'Universities': 'The College of Westchester', 'GPA': '3.15'}
{'Universities': 'Massachusetts State University', 'GPA': '2.75'}
{'Universities': 'Capella University', 'GPA': '2.8 – may accept students with low GPAs based on other aspects of their profiles'}
{'Universities': 'Cal Poly Pomona', 'GPA': '2.5'}
{'Universities': 'California State University East Bay', 'GPA': '2.5'}
{'Universities': 'CSU Fresno', 'GPA': '2.5'}
{'Universities': 'California State University Fullerton', 'GPA': '3.0'}
{'Universities': 'CSU Long Beach', 'GPA': '2.5'}
{'Universities': 'California State University Northridge', 'GPA': '3.0'}
{'Universities': 'Grand Canyon University', 'GPA': '3.0 – this is valid for most programs at the university, except for some like Ph.D. in General Psychology, which needs a 3.4 GPA'}
{'Universities': 'DePaul University', 'GPA': '2.5'}
{'Universities': 'Eastern Michigan University', 'GPA': '3.0'}
{'Universities': 'Gannon University', 'GPA': '3.5'}
{'Universities': 'Humboldt State University', 'GPA': '2.7'}
{'Universities': 'Jackson state university', 'GPA': '3.0'}
{'Universities': 'Full Sail University Winter Park, Florida', 'GPA': '2.0 – This is one of the Universities that accept low GPA for graduate programs'}
{'Universities': 'University of Minnesota Twin Cities', 'GPA': '3.0'}
{'Universities': 'Fresno City College', 'GPA': '2.0'}
{'Universities': 'Vorhees College', 'GPA': '2.0'}
{'Universities': 'Livingstone College', 'GPA': '2.32'}
{'Universities': 'McHenry County College', 'GPA': '2.0'}
{'Universities': 'Arkansas Tech University Russellville, Arkansas', 'GPA': '2.5'}
{'Universities': 'South Suburban College', 'GPA': '2.0'}
{'Universities': 'Southern University at New Orleans', 'GPA': '3.0'}
{'Universities': 'Talladega College', 'GPA': '2.0'}
{'Universities': 'Richland Community College', 'GPA': '2.15'}
{'Universities': 'Louisburg College', 'GPA': '2.0'}
{'Universities': 'Metropolitan College of New York', 'GPA': '2.5'}
{'Universities': 'National University San Diego, California', 'GPA': '2.0'}
{'Universities': 'Virginia University of Lynchburg', 'GPA': '2.8'}
{'Universities': 'Benjamin Franklin Institute of Technology', 'GPA': '3.15'}
{'Universities': 'Southeast Technical Institute', 'GPA': '3.3'}
{'Universities': 'University of the West', 'GPA': '3.25'}
{'Universities': 'Nebraska Wesleyan University Lincoln, Nebraska', 'GPA': '2.67'}
{'Universities': 'The University of North Carolina at Pembroke', 'GPA': '3.0'}
{'Universities': 'University of Pittsburgh at Bradford', 'GPA': '3.31'}
{'Universities': 'The University of South Carolina Beaufort', 'GPA': '3.5'}
{'Universities': 'University of Tennessee at Chattanooga', 'GPA': '3.0'}
{'Universities': 'State University of New York Brockport, New York', 'GPA': '3.0'}
{'Universities': 'The University of Texas at Tyler', 'GPA': '2.75'}
{'Universities': 'University of Washington Tacoma', 'GPA': '3.0'}
{'Universities': 'The University of Wisconsin Parkside', 'GPA': '3.0'}
{'Universities': 'Arkansas State University', 'GPA': '2.75'}
{'Universities': 'Arkansas Tech University', 'GPA': '2.5'}
{'Universities': 'Bradley University', 'GPA': '3.0'}
{'Universities': 'Colorado State University, Global Campus', 'GPA': '3.0'}
{'Universities': 'Northcentral University', 'GPA': '3.0'}
{'Universities': 'Strayer University', 'GPA': '2.5 – This is valid for most programs at the university'}
{'Universities': 'Connecticut State University', 'GPA': '3.0'}
{'Universities': 'University of Hawaii', 'GPA': '3.0'}
{'Universities': 'The CUNY system in NYC', 'GPA': '3.0'}
{'Universities': 'The Oregon University', 'GPA': '3.0'}
{'Universities': 'University of Rhode Island', 'GPA': '3.0'}
{'Universities': 'California State University Channel Islands, California', 'GPA': '2.5'}
{'Universities': 'Indiana University Northwest', 'GPA': '2.75'}
{'Universities': 'University of Michigan at Flint', 'GPA': '3.4'}
{'Universities': 'The University of Minnesota Crookston', 'GPA': '3.75'}
{'Universities': 'University of Missouri Kansas City', 'GPA': '3.0'}
{'Universities': 'The University of Nebraska at Kearney', 'GPA': '2.75'}
{'Universities': 'Louisiana State University Shreveport', 'GPA': '3.0'}
{'Universities': 'Southeast Missouri State University Cape Girardeau, Missouri', 'GPA': '3.0'}
{'Universities': 'Tiffin University Tiffin, Ohio', 'GPA': '2.0'}
{'Universities': 'Plymouth State University Plymouth, New Hampshire', 'GPA': '3.0'}
{'Universities': 'Metropolitan College of New York New York City, New York', 'GPA': '2.5'}
{'Universities': 'City University of Seattle Seattle, Washington', 'GPA': '3.0 on 4 point scale'}
{'Universities': 'Northwood University Midland, Michigan', 'GPA': '2.7'}
{'Universities': 'University of Mississippi Oxford, Mississippi', 'GPA': '3.0'}
{'Universities': 'Western Washington University Bellingham, Washington', 'GPA': '3.0 on 4 point scale'}
{'Universities': 'Arizona State University Phoenix, Arizona', 'GPA': '3.0 on 4 point scale'}
{'Universities': 'University of Minnesota Twin Cities', 'GPA': '3.0 on 4 point scale'}

In [41]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Specify the URL
url = 'https://ischoolconnect.com/blog/list-of-100-graduate-schools-with-low-gpa-requirements/'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}
response = requests.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the table element
    tables = soup.find_all('table')

    # Initialize lists to store data
    universities = []
    cgpa_requirements = []

    # Loop through rows in the table
    for table in tables:
        for row in table.find_all('tr'):
            columns = row.find_all('td')
            if len(columns) == 2:
                university = columns[0].text.strip()
                cgpa = columns[1].text.strip()
                universities.append(university)
                cgpa_requirements.append(cgpa)

    # Create a DataFrame from the lists
    data = {
        'Universities': universities,
        'GPA': cgpa_requirements
    }
    df = pd.DataFrame(data)

    # Print the DataFrame
    print(df)
else:
    print(f"Failed to retrieve the page. Status code: {response.status_code}")

                                          Universities                   GPA
0                                         Universities                  CGPA
1                University of Arkansas at Little Rock                   2.0
2           University of Colorado at Colorado Springs                  3.25
3                         Western Governors University                   2.0
4                    University of Louisiana at Monroe                   2.5
..                                                 ...                   ...
96              Northwood University Midland, Michigan                   2.7
97       University of Mississippi Oxford, Mississippi                   3.0
98   Western Washington University Bellingham, Wash...  3.0 on 4 point scale
99           Arizona State University Phoenix, Arizona  3.0 on 4 point scale
100                University of Minnesota Twin Cities  3.0 on 4 point scale

[101 rows x 2 columns]

In [42]:
df=df.drop(0)

In [43]:
df.head()

                                 Universities   GPA
1       University of Arkansas at Little Rock   2.0
2  University of Colorado at Colorado Springs  3.25
3                Western Governors University   2.0
4           University of Louisiana at Monroe   2.5
5     The University of Maine at Presque Isle   2.5

In [28]:
import pandas as pd

def convert_column_to_float(df, column_name):
    """
    Convert a column in a DataFrame to float.

    Args:
        df (pd.DataFrame): The DataFrame.
        column_name (str): The name of the column to convert.

    Returns:
        pd.DataFrame: The DataFrame with the specified column converted to float.
    """
    df[column_name] = df[column_name].apply(lambda x: float(x) if pd.notna(x) else None)
    return df

# Example usage:
# Assuming you already have a DataFrame 'df' with a 'GPA' column
# Convert the 'GPA' column to float
df = convert_column_to_float(df, 'GPA')

ValueError: could not convert string to float: '2.5 – may accept students with low GPAs based on other aspects of their profiles'

In [44]:
import pandas as pd
import re

def convert_column_to_float(df, column_name):
    """
    Convert a column in a DataFrame to float by extracting the numeric part.

    Args:
        df (pd.DataFrame): The DataFrame.
        column_name (str): The name of the column to convert.

    Returns:
        pd.DataFrame: The DataFrame with the specified column converted to float.
    """
    # Use regular expression to extract the float part
    df[column_name] = df[column_name].str.extract(r'(\d+\.\d+)').astype(float)
    return df

In [45]:
# Assuming you already have a DataFrame 'df' with a 'GPA' column
# Convert the 'GPA' column to float while extracting the numeric part
df = convert_column_to_float(df, 'GPA')

In [46]:
# Assuming you have a DataFrame named 'df' with a 'GPA' column

# Filter the DataFrame to include only rows where 'GPA' is equal to 2.5
filtered_df = df[df['GPA'] == 2.5]

# Now 'filtered_df' contains only the rows where 'GPA' is equal to 2.5

In [49]:
df.to_csv("100 universities.csv",index=False)

In [50]:
import requests
from bs4 import BeautifulSoup

# Define the URL of the starting page
base_url = "https://unischolars.com/universities/uk?sort=popularity"

# Initialize lists to store university data
university_data = []

# Define the number of pages you want to scrape
num_pages = 5

for page in range(1, num_pages + 1):
    # Construct the URL for the current page
    url = f"{base_url}&page={page}"

    # Send an HTTP GET request
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the HTML content of the page
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find and extract university information
        universities = soup.find_all('div', class_='uni-box')
        for university in universities:
            name = university.find('h2').text.strip()
            location = university.find('span', class_='loc').text.strip()
            tuition_fee = university.find('p', class_='fees').text.strip()
            cost_of_living = university.find('p', class_='cost').text.strip()
            country_rank = university.find('p', class_='rank').text.strip()

            # Store the data in a dictionary
            university_info = {
                'Name': name,
                'Location': location,
                'Tuition Fee': tuition_fee,
                'Cost of Living': cost_of_living,
                'Country Rank': country_rank
            }

            university_data.append(university_info)

# Print the scraped data
for university_info in university_data:
    print(university_info)

In [51]:
import requests
from bs4 import BeautifulSoup

# Define the URL of the starting page
base_url = "https://unischolars.com/universities/uk?sort=popularity"

# Initialize lists to store university data
university_data = []

# Send an HTTP GET request
response = requests.get(base_url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find and extract university information
    universities = soup.find_all('div', class_='universityPageStyles_UniversityCard__2-cFL')
    for university in universities:
        name = university.find('h3', {'data-cy': 'university_name'}).text.strip()
        location = university.find('p', {'data-cy': 'university_location'}).text.strip()
        tuition_fee = university.find('h5', {'data-cy': 'university_tuition_fee'}).text.strip()
        cost_of_living = university.find('h5', {'data-cy': 'university_cost_of_living'}).text.strip()
        country_rank = university.find('h5', {'data-cy': 'university_country_rank'}).text.strip()

        # Store the data in a dictionary
        university_info = {
            'Name': name,
            'Location': location,
            'Tuition Fee': tuition_fee,
            'Cost of Living': cost_of_living,
            'Country Rank': country_rank
        }

        university_data.append(university_info)

    # Print the scraped data
    for university_info in university_data:
        print(university_info)
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

AttributeError: 'NoneType' object has no attribute 'text'

In [53]:
import requests
from bs4 import BeautifulSoup

# Define the URL of the starting page
base_url = "https://unischolars.com/universities/uk?sort=popularity"

# Initialize lists to store university data
university_data = []

# Send an HTTP GET request
response = requests.get(base_url)

# Check if the request was successful
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find and extract university information
    universities = soup.find_all('div', class_='universityPageStyles_UniversityCard__2-cFL')
    for university in universities:
        name_element = university.find('h3', {'data-cy': 'university_name'})
        location_element = university.find('p', {'data-cy': 'university_location'})
        tuition_fee_element = university.find('h5', {'data-cy': 'university_tuition_fee'})
        cost_of_living_element = university.find('h5', {'data-cy': 'university_cost_of_living'})
        country_rank_element = university.find('h5', {'data-cy': 'university_country_rank'})

        # Check if the elements exist before accessing their text
        if name_element and location_element and tuition_fee_element and cost_of_living_element and country_rank_element:
            name = name_element.text.strip()
            location = location_element.text.strip()
            tuition_fee = tuition_fee_element.text.strip()
            cost_of_living = cost_of_living_element.text.strip()
            country_rank = country_rank_element.text.strip()

            # Store the data in a dictionary
            university_info = {
                'Name': name,
                'Location': location,
                'Tuition Fee': tuition_fee,
                'Cost of Living': cost_of_living,
                'Country Rank': country_rank
            }

            university_data.append(university_info)

    # Print the scraped data
    for university_info in university_data:
        print(university_info)
else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

In [55]:
import requests
from bs4 import BeautifulSoup

# Define the base URL
base_url = "https://unischolars.com/universities/uk?sort=popularity"

# Define headers to mimic a real browser
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}

# Send an HTTP GET request to the URL with headers
response = requests.get(base_url, headers=headers)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the page using BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find and extract the university information
    universities = soup.find_all('div', class_='universityPageStyles_UniversityCard__2-cFL')

    for university in universities:
        name_element = university.find('h3', {'data-cy': 'university_name'})
        location_element = university.find('p', {'data-cy': 'university_location'})
        tuition_fee_element = university.find('h5', {'data-cy': 'university_tuition_fee'})
        cost_of_living_element = university.find('h5', {'data-cy': 'university_cost_of_living'})
        country_rank_element = university.find('h5', {'data-cy': 'university_country_rank'})

        # Check if elements are not None before extracting text
        if name_element:
            name = name_element.text.strip()
        else:
            name = "N/A"

        if location_element:
            location = location_element.text.strip()
        else:
            location = "N/A"

        if tuition_fee_element:
            tuition_fee = tuition_fee_element.text.strip()
        else:
            tuition_fee = "N/A"

        if cost_of_living_element:
            cost_of_living = cost_of_living_element.text.strip()
        else:
            cost_of_living = "N/A"

        if country_rank_element:
            country_rank = country_rank_element.text.strip()
        else:
            country_rank = "N/A"

        # Print the extracted information
        print(f"University Name: {name}")
        print(f"Location: {location}")
        print(f"Tuition Fee: {tuition_fee}")
        print(f"Cost of Living: {cost_of_living}")
        print(f"Country Rank: {country_rank}")
        print("\n")

else:
    print(f"Failed to retrieve data. Status code: {response.status_code} - URL: {base_url}")

University Name: University of Warwick
Location: Coventry, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: Queen Mary University of London
Location: London, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: Cardiff University
Location: Cardiff, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: London School of Economics
Location: London, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: University of Leicester
Location: Leicester, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: Brunel University London
Location: London, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: City, University of London
Location: London, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: University of Portsmouth
Location: Portsmouth, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: Northumbria University
Location: Newcastle, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A


University Name: Nottingham Trent University
Location: Nottingham, United Kingdom
Tuition Fee: N/A
Cost of Living: N/A
Country Rank: N/A

In [60]:
import requests
from bs4 import BeautifulSoup

# URL of the page to scrape
url = "https://unischolars.com/universities/uk?sort=popularity"

# Headers to mimic a browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.1000.0 Safari/537.36"
}

# Send an HTTP GET request to the URL
response = requests.get(url, headers=headers)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content with BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find all university cards on the page
    university_cards = soup.find_all('div', class_='universityPageStyles_UniversityCard__2-cFL')

    # Loop through each university card and extract information
    for card in university_cards:
        name = card.find('h3', {'data-cy': 'university_name'}).text.strip()
        location = card.find('p', {'data-cy': 'university_location'}).text.strip()
        
        # Extract cost of living, tuition fee, and country rank
        cost_of_living_elem = card.find('div', {'data-cy': 'university_cost_of_living'})
        tuition_fee_elem = card.find('div', {'data-cy': 'university_tuition_fee'})
        country_rank_elem = card.find('div', {'data-cy': 'university_country_rank'})
        
        cost_of_living = cost_of_living_elem.find('h5').text.strip() if cost_of_living_elem else 'N/A'
        tuition_fee = tuition_fee_elem.find('h5').text.strip() if tuition_fee_elem else 'N/A'
        country_rank = country_rank_elem.find('h5').text.strip() if country_rank_elem else 'N/A'

        # Print the extracted information for each university
        print(f"University Name: {name}")
        print(f"Location: {location}")
        print(f"Cost of Living: {cost_of_living}")
        print(f"Tuition Fee: {tuition_fee}")
        print(f"Country Rank: {country_rank}")
        print("\n" + "=" * 50 + "\n")

else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

University Name: University of Warwick
Location: Coventry, United Kingdom
Cost of Living: £ 15,888
Tuition Fee: £ 26,470
Country Rank: #10

==================================================

University Name: Queen Mary University of London
Location: London, United Kingdom
Cost of Living: £ 22,932
Tuition Fee: £ 9,650
Country Rank: #15

==================================================

University Name: Cardiff University
Location: Cardiff, United Kingdom
Cost of Living: £ 12,546
Tuition Fee: £ 17,450
Country Rank: #18

==================================================

University Name: London School of Economics
Location: London, United Kingdom
Cost of Living: £ 22,932
Tuition Fee: £ 20,136
Country Rank: #20

==================================================

University Name: University of Leicester
Location: Leicester, United Kingdom
Cost of Living: £ 11,342
Tuition Fee: £ 15,500
Country Rank: #22

==================================================

University Name: Brunel University London
Location: London, United Kingdom
Cost of Living: £ 22,932
Tuition Fee: £ 8,700
Country Rank: #39

==================================================

University Name: City, University of London
Location: London, United Kingdom
Cost of Living: £ 22,932
Tuition Fee: £ 6,900
Country Rank: #43

==================================================

University Name: University of Portsmouth
Location: Portsmouth, United Kingdom
Cost of Living: £ 14,316
Tuition Fee: £ 7,900
Country Rank: #46

==================================================

University Name: Northumbria University
Location: Newcastle, United Kingdom
Cost of Living: £ 12,230
Tuition Fee: £ 12,950
Country Rank: #47

==================================================

University Name: Nottingham Trent University
Location: Nottingham, United Kingdom
Cost of Living: £ 14,868
Tuition Fee: £ 11,950
Country Rank: #51

==================================================

In [63]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Define the base URL
base_url = "https://unischolars.com/universities/uk?sort=popularity&page="

# Headers to mimic a browser request
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.1000.0 Safari/537.36"
}

# Define the number of pages you want to scrape
num_pages = 24  # You can change this to the number of pages you want

# Create an empty DataFrame to store the data
data = []

# Loop through each page
for page_number in range(1, num_pages + 1):
    # Construct the URL for the current page
    url = base_url + str(page_number)

    # Send an HTTP GET request to the URL
    response = requests.get(url, headers=headers)

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Parse the HTML content with BeautifulSoup
        soup = BeautifulSoup(response.text, 'html.parser')

        # Find all university cards on the page
        university_cards = soup.find_all('div', class_='universityPageStyles_UniversityCard__2-cFL')

        # Loop through each university card and extract information
        for card in university_cards:
            name = card.find('h3', {'data-cy': 'university_name'}).text.strip()
            location = card.find('p', {'data-cy': 'university_location'}).text.strip()

            # Extract cost of living, tuition fee, and country rank
            cost_of_living_elem = card.find('div', {'data-cy': 'university_cost_of_living'})
            tuition_fee_elem = card.find('div', {'data-cy': 'university_tuition_fee'})
            country_rank_elem = card.find('div', {'data-cy': 'university_country_rank'})

            cost_of_living = cost_of_living_elem.find('h5').text.strip() if cost_of_living_elem else 'N/A'
            tuition_fee = tuition_fee_elem.find('h5').text.strip() if tuition_fee_elem else 'N/A'
            country_rank = country_rank_elem.find('h5').text.strip() if country_rank_elem else 'N/A'

            # Append the extracted data to the 'data' list
            data.append([name, location, cost_of_living, tuition_fee, country_rank])

    else:
        print(f"Failed to retrieve data from page {page_number}. Status code: {response.status_code}")

# Create a DataFrame from the collected data
df = pd.DataFrame(data, columns=["University Name", "Location", "Cost of Living", "Tuition Fee", "Country Rank"])

# Print the DataFrame

In [65]:
df.head()

,University Name,Location,Cost of Living,Tuition Fee,Country Rank
0,University of Warwick,"Coventry, United Kingdom","£ 15,888","£ 26,470",#10
1,Queen Mary University of London,"London, United Kingdom","£ 22,932","£ 9,650",#15
2,Cardiff University,"Cardiff, United Kingdom","£ 12,546","£ 17,450",#18
3,London School of Economics,"London, United Kingdom","£ 22,932","£ 20,136",#20
4,University of Leicester,"Leicester, United Kingdom","£ 11,342","£ 15,500",#22

In [66]:
df.to_excel("UK universities For Finance.csv",index=False)